#!/usr/bin/env python3
"""Pre-compress the embedded capture viewer for the WebAP.

The viewer is a single 369 KB HTML file embedded in the app image, and it was
being embedded and served uncompressed. It gzips 3.3:1, which is a quarter of a
megabyte of the 3 MiB app partition.

The complication is `/report.html`, which does not serve the file whole: it
splices the capture stream into a data island in the middle of it, so there is
no static byte sequence to compress ahead of time.

The trick is to build **one** gzip member with a runtime-sized hole:

    gzip header
    deflate(head)         ends with Z_FULL_FLUSH -> byte-aligned, no final block
    stored blocks         emitted at request time, one per chunk, BFINAL=0
    deflate(tail)         ends with Z_FINISH -> final block
    gzip trailer          CRC32 and ISIZE of head+island+tail

Both boundaries are byte-aligned, so the three pieces concatenate into a valid
deflate stream. The tail is compressed against an empty history, which is fine:
its back-references only reach within itself, and a decoder that has already
emitted head+island simply never looks that far back.

The trailer needs the CRC of the whole uncompressed document, which the device
cannot compute because it no longer holds the plain head and tail. It doesn't
need to: this script records their CRCs and lengths, and the firmware combines
them with the island's CRC using the standard GF(2) crc32_combine.

The island is *stored*, not compressed. That matches what the device sends
today (nothing was compressed before), costs 5 bytes per 64 KB, and keeps the
per-request CPU cost at one CRC pass.

Outputs, all into the build directory:
    viewer_head.deflate   raw deflate, full-flush terminated
    viewer_tail.deflate   raw deflate, final block
    viewer_gz_meta.h      lengths and CRCs for the trailer
"""

import os
import struct
import sys
import zlib

MARKER = b"<!--SC_DATA_ISLAND-->"


def build(src_path, out_dir):
    src = open(src_path, "rb").read()
    if src.count(MARKER) != 1:
        sys.exit("gen_viewer_gz: expected exactly one %s in %s, found %d"
                 % (MARKER.decode(), src_path, src.count(MARKER)))

    cut = src.index(MARKER)
    head, tail = src[:cut], src[cut + len(MARKER):]

    # Z_FULL_FLUSH: byte-aligns and resets the dictionary without setting
    # BFINAL, so stored blocks can follow it directly.
    co = zlib.compressobj(9, zlib.DEFLATED, -15)
    head_z = co.compress(head) + co.flush(zlib.Z_FULL_FLUSH)

    co = zlib.compressobj(9, zlib.DEFLATED, -15)
    tail_z = co.compress(tail) + co.flush(zlib.Z_FINISH)

    os.makedirs(out_dir, exist_ok=True)
    head_p = os.path.join(out_dir, "viewer_head.deflate")
    tail_p = os.path.join(out_dir, "viewer_tail.deflate")
    meta_p = os.path.join(out_dir, "viewer_gz_meta.h")

    with open(head_p, "wb") as f:
        f.write(head_z)
    with open(tail_p, "wb") as f:
        f.write(tail_z)

    meta = f"""/* Generated by tools/gen_viewer_gz.py — do not edit.
 *
 * Source: {os.path.basename(src_path)}
 * The viewer is embedded as two raw-deflate halves around a runtime data
 * island; see the script header for the stream layout.
 */
#pragma once

#define VIEWER_GZ_HEAD_RAW_LEN  {len(head)}u
#define VIEWER_GZ_HEAD_RAW_CRC  0x{zlib.crc32(head):08x}u
#define VIEWER_GZ_TAIL_RAW_LEN  {len(tail)}u
#define VIEWER_GZ_TAIL_RAW_CRC  0x{zlib.crc32(tail):08x}u

/* Uncompressed size of the document with an empty island — what /viewer sends. */
#define VIEWER_GZ_SHELL_RAW_LEN ({len(head)}u + {len(tail)}u)

/* For the build log / space_budget.md. */
#define VIEWER_GZ_SRC_LEN       {len(src)}u
#define VIEWER_GZ_EMBEDDED_LEN  ({len(head_z)}u + {len(tail_z)}u)
"""
    with open(meta_p, "w") as f:
        f.write(meta)

    saved = len(src) - (len(head_z) + len(tail_z))
    print("gen_viewer_gz: %d -> %d + %d = %d embedded (saves %d B, %.1f KiB)"
          % (len(src), len(head_z), len(tail_z),
             len(head_z) + len(tail_z), saved, saved / 1024.0))
    return head, tail, head_z, tail_z


# ---- self-check ---------------------------------------------------------
# Runs on every build. If the stream ever stops round-tripping, the build
# fails here rather than the device serving an undecodable page.

def stored_blocks(data):
    out = b""
    for off in range(0, len(data), 65535):
        piece = data[off:off + 65535]
        out += b"\x00" + struct.pack("<HH", len(piece), 0xFFFF ^ len(piece)) + piece
    return out


def crc32_combine(crc1, crc2, len2):
    """Same GF(2) method as zlib's crc32_combine; mirrored in viewer_gz.c."""
    def mat_times(mat, vec):
        acc, i = 0, 0
        while vec:
            if vec & 1:
                acc ^= mat[i]
            vec >>= 1
            i += 1
        return acc

    def mat_square(dst, src):
        for n in range(32):
            dst[n] = mat_times(src, src[n])

    if len2 == 0:
        return crc1
    odd = [0] * 32
    even = [0] * 32
    odd[0] = 0xEDB88320
    row = 1
    for n in range(1, 32):
        odd[n] = row
        row <<= 1
    mat_square(even, odd)
    mat_square(odd, even)
    while True:
        mat_square(even, odd)
        if len2 & 1:
            crc1 = mat_times(even, crc1)
        len2 >>= 1
        if len2 == 0:
            break
        mat_square(odd, even)
        if len2 & 1:
            crc1 = mat_times(odd, crc1)
        len2 >>= 1
        if len2 == 0:
            break
    return crc1 ^ crc2


def selfcheck(head, tail, head_z, tail_z):
    import gzip as gzmod
    cases = [
        b"",
        b'{"a":1}\n',
        b'x' * 65535,                      # exactly one stored block
        b'y' * 65536,                      # forces a second block
        (b'{"rec":"' + b'A' * 120 + b'"}\n') * 700,
    ]
    for island in cases:
        # Byte-for-byte the header viewer_gz_begin() emits, so the self-check
        # validates the stream the device actually sends.
        body = (b"\x1f\x8b\x08\x00\x00\x00\x00\x00\x02\xff"
                + head_z + stored_blocks(island) + tail_z)
        crc = crc32_combine(
            crc32_combine(zlib.crc32(head), zlib.crc32(island), len(island)),
            zlib.crc32(tail), len(tail))
        total = (len(head) + len(island) + len(tail)) & 0xFFFFFFFF
        body += struct.pack("<II", crc, total)
        if gzmod.decompress(body) != head + island + tail:
            sys.exit("gen_viewer_gz: SELF-CHECK FAILED for island of %d bytes"
                     % len(island))
    print("gen_viewer_gz: self-check OK (%d island shapes round-tripped)"
          % len(cases))


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit("usage: gen_viewer_gz.py <index.html> <out-dir>")
    selfcheck(*build(sys.argv[1], sys.argv[2]))
